version: "3.9"

services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000"]

  mysql:
    image: mysql:8.0        # MySQL version (can change if needed)
    container_name: mysql_container
    restart: always         # automatically restart if container crashes
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # set root password
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # create a database at startup
      MYSQL_USER: ${MYSQL_USER}                    # create a custom user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # password for the custom user
    ports:
      - "3307:3306"          # map host 3307 -> container 3306
    volumes:
      - mysql_data:/var/lib/mysql   # persist database data

  adminer:
    image: adminer
    container_name: adminer_ui  
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:

