# Generated by Django 5.2.5 on 2025-09-05 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('copies', models.IntegerField()),
                ('available', models.IntegerField(default=1)),
            ],
        ),
    ]
